  db:
    container_name: reflect_db
    image: mysql:8.0.20
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=reflect
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306